### ISSUE TITLE
Meshnet questions

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/organizing#17]
This issue collects a list of questions that the prototyping process needs to answer.

_The top message will be updated as more questions emerge that I don't currently have an answer for. Please add questions to the thread._

---

- [ ] Will/should I be able to host a service on the network from my laptop that is connected to the network? Or will I need to bring a microcomputer (e.g. rpi) and plug into one of these official planned nodes?

**Comment by gobengo** [comment]
Naive solutions:
* Just start a wiki page here for people to reserve/request an IP for a service. "registry approach".
* Based on a future attendee database, pre-allocate N addresses for each attendee and email it to them

@sudomesh runs a deployment of https://github.com/sudomesh/notdhcp, and newly booted devices ask it for an unused ip , but I never understood why we couldn't just run a normal dhcp server. @juul might know.

**Comment by benhylau** [comment]
My understanding is that notdhcp is quite specific to the People's Open's "stack":

>Q: Why did you write this? Why not just use the dnsmasq dhcp server?

>A: The behaviour we want is very specific. nothdcpserver hands out only one IP per interface and does not keep track of lease time. Every time there is a physical disconnect on the interface the state is reset. dnsmasq uses the IP of each interface to decide which dhcp-range to hand out on that interface. This is problematic since we use the same IP on multiple non-bridged interfaces. We still use dnsmasq for normal DHCP. We are also handing out an SSL cert and key along with the IP. Lastly, we don't want to give these IPs out to anything that isn't an extender node and we want to run both notdhcpserver and dnsmasq dhcp server on the same interface at the same time such that the interface can work as an extra LAN port until an extender node is plugged in, at which time it will be switched over to become a dedicated extender node port.

Perhaps a registry can be used for some DNS thing at the venue, but I think IP assignment should be autonomous, whenever a device connects. But we need to protect against people accidentally running a second DHCP server on the network... etc.

I almost want to run a self-addressed v6-only network, but many applications will probably fail catastrophically. Feature or bug 🤔
