### ISSUE TITLE
Create process for applying to be Build Volunteer (24 hours) for 100% rebate.

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/organizing#21]

**Comment by whanamura** [comment]
Here's where we are headed with Volunteer sign ups:
https://docs.google.com/document/d/1sBNCFyvH8xG60UzjJGqqjtVhzzrGX2gx6dZ9FrL8cmk/edit?usp=sharing

DRAFT FORM:
https://docs.google.com/forms/d/1ZcfuMXGFCl6dD29kLDtu2K6H5Ln7iDoYnQk-d3TTO0o/edit
