### ISSUE TITLE
Create process for applying to be Volunteer (12 hours) for 50% rebate

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/organizing#22]

**Comment by whanamura** [comment]
Today we started to draft the Volunteer Fellowship process.  Here are some early drafts:

VOLUNTEER WITH US
Seeking Volunteers for the DWeb Camp 2019

DWeb Camp is a community-created event, fueled by the vision, talent, and creativity of those who participate. DWeb camp will be built and run primarily with volunteer power. So are you a team player, a builder, a DIY maven who loves the outdoors? Can you paint a sign, chop vegetables, or lay cables? Is erecting a 30 foot dome structure your jam? Are you a thrifty maker, known for turning discarded items into gold?  

Then we are looking for you! We seek up to 75 volunteer fellows who will trade their services for ticket reimbursements of 50% or 100%.

Start out by telling us about yourself and the talents you can bring to these volunteer teams. Then we’ll be in touch directly.

**Comment by whanamura** [comment]
Here's the first draft of the Volunteer Application Form:  https://docs.google.com/forms/d/1ZcfuMXGFCl6dD29kLDtu2K6H5Ln7iDoYnQk-d3TTO0o/edit
