### ISSUE TITLE
Recruit Creative Team Director-- to coordinate the creative projects, requests for support, etc.

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/organizing#39]

**Comment by whanamura** [comment]
Created first draft here:
https://docs.google.com/document/d/15C69EGt2xRE04YUb7nooGIuyv1bKMm_rrWFCkNadfHQ/edit?ts=5c9d6446

Job being split between Pamela Pascual and Andi Wong.

**Comment by benhylau** [comment]
@whanamura doc needs public view permission, now it asks me to request permission
