### ISSUE TITLE
Find inspiration/guidance in Chaos Communications Camp documentation

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/organizing#4]

**Comment by whanamura** [comment]
Good references:

CCC Wiki (with 6-2-1 rule!): https://events.ccc.de/congress/2018/wiki/index.php/Main_Page 

In particular look at the "How to participate" section. Here's an example of "cluster" of "assemblies": https://events.ccc.de/congress/2018/wiki/index.php/Assembly:Critical_Decentralisation_Cluster 

the tea house: https://events.ccc.de/congress/2015/wiki/Assembly:TeaHouse
