### ISSUE TITLE
Organizers to join Patchwork

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/organizing#5]
You can [download Patchwork here](https://ahdinosaur.github.io/patchwork-downloader/).

The SSB folks have taken a lot of care to write friendly onboard documents, so if you run into any trouble you can follow the [Quick Start steps](https://www.scuttlebutt.nz).

Steps 3 says "Go to the list of pub servers and get an invite code from one.” but you can also use this one run by @darkdrgn2k from Toronto Mesh:

```
ssb.e-mesh.net:8008:@AWf8Wn299ZUH7t+JAJL6B217LhDxfHEjgoGOXoYmNjY=.ed25519~z/8xEQWBDk/th68yZ6mPmvBdYv63r0/KnramPnzBGDI=
```

After you add your first pub, your computer may get very busy syncing up :) give it some time and soon you’ll be able to search up people in the search box and start adding Friends, by name or by key. You can add @benhylau with key `@Ys9lgBLC0MfPUQrbqd0hddjbjElx7ZNvtikxvMIaqgs=.ed25519`

You should also starting seeing your feed fill up with messages of the people (or topics) you follow. Let me know if you run into any trouble :)

**Comment by mixmix** [comment]
Hi, I'm a friendly scuttlebutt peer! If anyone has any questions, please feel free to hit me up directly : mix@protozoa.nz  or @whimful on twitter. I'm `@ye+QM09iPcDJD6YvQYjoQc7sLF/IFhmNbEqgdzQo3lQ=.ed25519` on scuttlebutt.

**Comment by whanamura** [comment]
I'm now on Scuttlebutt's Patchwork!
My name: FlowerVillage
My hash:  @yhF7gkOwDb8cLLa4Ejq2Bh7C2RujWL2EPYYXcmu2+H8=.ed25519

Come find me!
