### ISSUE TITLE
Recruit Global Fellows Coordinator

### ISSUE THREAD

**Issue by whanamura** [dweb-camp-2019/organizing#56]

**Comment by whanamura** [comment]
**DWeb Camp is seeking a dynamic, globally-minded, well-organizaed volunteer to co-create and run the Global Fellows Program 2019.** 

We are fundraising to support 10+ Global Fellows to attend DWeb Camp.  The ideal Dweb Camp Fellow represents projects that could really use the decentralized technologies that we will be building and testing at the camp.  Fellows work closely with under-resourced communities; they can be bridges between the technologies being developed and the communities who would benefit from them most.  Often times these communities exist where there is no internet, it is too expensive to afford, or where access is censored or surveilled.  

**The Global Fellows Coordinator would:**

- help create the application form
--architect the application/selection process
--do outreach with other organizations and individuals to find great candidates
--chair the selection committee
--be the implementer in getting Fellows the stipend (approx. $2200) in travel support
--be responsible for getting the proper documentation, receipts, and/or forms for tax purposes
--help raise more funds to support Global Fellows (if you feel moved to do this too!)
--help to ensure that the Global Fellows are supported, welcomed, and well integrated into every aspect of the camp experience.


-

**Comment by whanamura** [comment]
We also need a small committee to work with Mai Sutton, Associate Producer, to review and support Global Fellows.  Help us make this a great experience for all our Global Fellows!

**Comment by benhylau** [comment]
I can help with this since I am already in touch with a few groups re:

>do outreach with other organizations and individuals to find great candidates
