### ISSUE TITLE
Set up bi-weekly Q&A open calls

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/organizing#59]
Anyone can call in to ask questions about DWeb Camp 2019, from registration to project proposals. Organizers should all try to call in, but we need facilitator to always be there.

Let's aim to publish the call hours when we launch website.

**Comment by maisutton** [comment]
We decided to have them on the following dates and times on Jitsi: 
Wed May 1 11 AM 
Wed May 15, 6 PM
Wed May 29 1 PM
Wed June 12 11 AM
Wed June 26 6 PM
Wed July 3 11 AM
Wed July 10 6 PM

**Comment by maisutton** [comment]
Are we going to use https://meet.jit.si/dwebcamp for the calls?
