### ISSUE TITLE
Publishing notes from our weekly syncs

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/organizing#61]
@whanamura our first weekly sync notes is now in Google Doc, how can we publish those? Shall we link to them from the main README in this repo? If that's the case, we should make them world-readable, I think they are currently world-writable.

**Comment by ArtsEd4All** [comment]
@whanamura @benhylau @amberinitiative I added a "stream of consciousness" to the notes — Some connections & creative ideas that percolated from our discussions that I would like to explore. Are the weekly sync notes the right place to share this info or should I move the information elsewhere? Is it purposeful or confusing to include my "weaving" of ideas inspired by the site — both the natural world / local artistic community here?

Can Mushrooms Save the Honey Bee?
https://movingart.com/can-mushrooms-save-honey-bee/

**Comment by amberinitiative** [comment]
Weekly Syncs are a good place under "stream of consciousness". I think it's good to have it connected to a single area where the discussion took place.

**Comment by benhylau** [comment]
Not sure if organizer syncs were published but open call notes are here https://github.com/dweb-camp-2019/organizing#open-dialogue-calls
