### ISSUE TITLE
Small Group Coordinator Needed: Organize 20-30 facilitators of Small Groups

### ISSUE THREAD

**Issue by whanamura** [dweb-camp-2019/organizing#76]
For 30 minutes each day, we want to break into small "check in" groups of 10, shepherded by a facilitator.  So we will need about 20-30 facilitators.

Looking for 1-2 people to 

- recruit and organize these facilitators,
--create a set of guidelines and expectations
--provide some training and guidance at camp
--Gather them at the right times each day (just before dinner).

Mikey Williams of Scuttlebutt has agreed to be one of the coordinators of Small Group Facilitation. Looking for another!

**Comment by whanamura** [comment]
Here are notes from our Organizers Meeting:
Small groups + leaders
Distribute work of keeping tabs on people and supporting them through the event
Can we facilitate finding 30 leaders?
Good idea for introverts
Use playing cards to divide people (ice breaker)
Large facilitated discussion / ice breaker activity to encourage people to meet each other 
Based on what people are there at the event for, such as knowledge, opportunities, etc.

**Comment by judytuna** [comment]
Is this the same as [Weavers](https://github.com/dweb-camp-2019/organizing/blob/master/roles/weavers.md)? Are y'all still looking for another facilitator-facilitator?
