### ISSUE TITLE
Review meshnet hardware used by existing communities

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/organizing#8]
What hardware is used by mesh communities and how are they using them:
- [NYC Mesh](https://docs.nycmesh.net/hardware/)
- [People's Open](https://sudoroom.org/wiki/Mesh/Home_and_extender_nodes)
- [Freifunk](https://wiki.freifunk.net/hardware)
- [Guifi](https://people.ac.upc.edu/leandro/docs/analysis.pdf) -- this one is more high level and related to backhaul than radio equipment
- [Altermundi / LibreRouter](http://blog.altermundi.net/article/librerouter-fase-ii/)
- [LibreMesh](https://libremesh.org/docs/hardware/index.html)

**Comment by gobengo** [comment]
Hi @benhylau . I think we met at the dweb summit last Summer. I assume other https://github.com/sudomesh ("People's Open" above) peeps would be excited to help set up the network at the camp out (I'll be there too, but in South America until July). /cc @maisutton @jnny @eenblam @bennlich

At the very least they have experience setting up a mesh with specific hardware and firmware. Usually N600s. https://sudoroom.org/wiki/Mesh/WalkThrough

**Comment by benhylau** [comment]
Hey @gobengo :) yes I am planning to ping People's Open to build this network together! Also going to try Babel since that's what their stack is based on. I have been speaking with @paidforby

I think we'd like an ac network though, which currently isn't really supported by the standard People's Open hardware, or the LibreRouter, so I have proposed something quite different but still hoping to use something Babel based #15 

The plan is that the couple days before the conference we'll build the infrastructure. Hopefully you'd be back to join us :)

**Comment by gobengo** [comment]
@benhylau Yep, I will.
