### ISSUE TITLE
Rename sessions on sched?

### ISSUE THREAD

**Issue by pospi** [dweb-camp-2019/organizing#82]
Looks like you can edit the *description* of events you've been set up to manage, but not the titles. Is this possible, or does it need to be a special request?

**Comment by whanamura** [comment]
Hi @popsi That may be so--it's hard for us to know b/c our view as ADMINs is different. In any case, just write to Ravi@archive.org and he can change anything you want.  So can your Space Steward, who should be writing to you shortly to confirm time, needs, date, etc.
Is there something you'd like to change?
