### ISSUE TITLE
Permission to create repos for projects

### ISSUE THREAD

**Issue by willemneal** [dweb-camp-2019/organizing#83]
Is it possible to be added to the organization so that I can create repos for projects?

**Comment by benhylau** [comment]
Hi @willemneal! What types of projects? Should they live in this repo or one that is not scoped to dweb-camp-2019?

**Comment by willemneal** [comment]
The idea at the time was to create a repo for a project idea I had for using two drones and a VR headset.  But now that I don't have access to either there is no longer a need for one.
